name: Next.js CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 20.x]

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js and cache dependencies
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install dependencies (npm install requires package-lock.json)
      - name: Install dependencies
        working-directory: Frontend/nextjs-dashboard
        run: |
          npm install --force
          npm install js-cookie --force

      # Step 4: Build the Next.js app
      - name: Build Next.js app
        working-directory: Frontend/nextjs-dashboard
        run: npm run build

      # Step 5: Run tests (optional)
      - name: Run tests
        working-directory: Frontend/nextjs-dashboard
        run: npm test

      # Step 6: Upload build artifacts (Optional)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: log_File
          path: ${{ github.workspace }}/
          if-no-files-found: error
          overwrite: true
