name: Setting up CI pipeline

on: 
  push:
    branches: 
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  # # Job 1: Encrypt the secret
  # github-secrets:
  #   runs-on: ubuntu-latest
  #   name: A Job to encrypt a secret
  #   steps:
  #     - id: read-secret
  #       shell: bash
  #       run: |
  #         # Read the secret from GitHub secrets
  #         OUR_SECRET=${{ secrets.SECRET_KEY }};
  #         # Encrypt the secret using OpenSSL
  #         BINARY_ENCRYPTED_SECRET=$(echo -n "$OUR_SECRET" | openssl enc -aes-256-cbc -pbkdf2 -salt -k "${{ secrets.ENCRYPTION_PASSWORD }}");
  #         # Encode the encrypted binary as base64
  #         ENCRYPTED_SECRET=$(echo -n "$BINARY_ENCRYPTED_SECRET" | base64);
  #         # Output the encrypted secret
  #         echo "our-secret=$ENCRYPTED_SECRET" >> $GITHUB_OUTPUT
  #   outputs:
  #     encrypted-secret: ${{ steps.read-secret.outputs.our-secret }}

  # Job 2: Build with encrypted secret
  build:
    # needs: github-secrets
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["pypy3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # # Decrypt the encrypted secret from Job 1
      # - id: decrypt-secret
      #   shell: bash
      #   run: |
      #     # Retrieve the encrypted secret from the previous job
      #     ENCRYPTED_SECRET=${{ needs.github-secrets.outputs.encrypted-secret }};
      #     # Decode the base64-encoded encrypted secret
      #     BINARY_ENCRYPTED_SECRET=$(echo -n "$ENCRYPTED_SECRET" | base64 --decode);
      #     # Decrypt the secret using OpenSSL and the encryption password
      #     OUR_SECRET=$(echo -n "$BINARY_ENCRYPTED_SECRET" | openssl enc -aes-256-cbc -pbkdf2 -d -salt -k "${{ secrets.ENCRYPTION_PASSWORD }}");
      #     # Save the decrypted secret to an environment variable or use it directly
      #     echo "our-secret=$OUR_SECRET" >> $GITHUB_ENV

      # Check Python version
      - name: Display python version
        run: |
          python -c "import sys; print(sys.version)"

      # Install dependencies
      - name: Install dependencies
        run: |
          mkdir logFile
          python -m pip install --upgrade pip
          pip install pylint Flask flask_cors firebase_admin

      # Firebase setup
      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools
          firebase login:ci
          firebase init

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          

      # Lint with Ruff
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check --output-format=github --exit-zero
        continue-on-error: true

      # Run tests using pytest
      - name: Check code using pytest
        run: |
          pip install pytest pytest-cov pytest-flask pytest-repeat
          pytest --maxfail=10 --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html --count=10

      # Compress and upload files
      - name: Compress and upload file
        uses: actions/upload-artifact@v4
        with:
          name: log_File
          path: ${{ github.workspace }}/
          if-no-files-found: error
          overwrite: true
